x=(input('Insira algo: '))
print(x, 'é do tipo primitivo', type(x))
print(x, 'possui apenas letras?', x.isalpha(), '!')
print(x, 'possui letra e número?', x.isalnum())
print(x, 'possuia apenas letras maiúsculas?', x.isupper())
print(x, 'possuia apenas letras minúsculas?', x.islower())